version: '3.7'

volumes:
  logview-es_vol01:

services:
 logview-es:
      restart: always
      environment:
         - discovery.type=single-node
      deploy:
         placement:
               #max_replicas_per_node: 1
               constraints:
                   - node.role == manager
      image: docker.adipsys.com:5000/logview-es
      volumes:
         - logview-es_vol01:/usr/share/elasticsearch/data
         #- /snapshots:/snapshots
         #- /root/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

 logview-ls:
      image: docker.adipsys.com:5000/logview-ls
      restart: always
      environment:
         - discovery.type=single-node
         - xpack.monitoring.elasticsearch.username=elastic
         - xpack.monitoring.elasticsearch.password=${ELASTICSEARCH_PASSWORD}
         - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
         - MQT_VENUE=${MQT_VENUE}
         - MQT_PASS=${MQT_PASS}
      #deploy:
       #  placement:
        #       max_replicas_per_node: 1
      ports:
              - target: 5014
                published: 5014
                protocol: udp
                mode: host
              - target: 5015
                published: 5015
                protocol: udp
                mode: host
              - target: 5045
                published: 5045
                protocol: udp
                mode: host
              - target: 5044
                published: 5044
                protocol: tcp
                mode: host
              #- 5014:5014/udp
              #- 5015:5015/udp
              #- 5045:5045/udp
              #- 5044:5044
      depends_on:
              - "logview-es"

 logview-kb:
      image: docker.adipsys.com:5000/logview-kb
      restart: always
      environment:
        - ELASTICSEARCH_HOSTS=http://logview-es:9200/
        - ELASTICSEARCH_USERNAME=kibana_system
        - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      #deploy:
       #  placement:
        #       max_replicas_per_node: 1
      ports:
              - ${WEB_IHM_PORT}:5601
      depends_on:
              - "logview-es"
              
 #dnsp-fb:
 #     image: docker.adipsys.com:5000/logview-fb
 #     restart: always
 #     volumes:
 #             - '/filebeat-input/:/filebeat-input/'
 #     depends_on:
 #             - "logview-es"
 #             - "logview-ls"
    
 #logview-mq:
 #     image: docker.adipsys.com:5000/logview-mq
 #     restart: always
 #     environment:
 #        - MQT_VENUE=${MQT_VENUE}
 #        - MQT_PASS=${MQT_PASS}
 #     ports:
 #             - 8883:8883
 #     depends_on:
 #             - "logview-ls"
