version: '3.7'

volumes:
  logview-es_vol01:

services:
 logview-es:
      restart: always
      environment:
         - discovery.type=single-node
      deploy:
         placement:
               #max_replicas_per_node: 1
               constraints:
                   - node.role == manager
      image: docker.adipsys.com:5000/logview-es
      volumes:
         - logview-es_vol01:/usr/share/elasticsearch/data

 logview-ls:
      image: docker.adipsys.com:5000/logview-ls
      restart: always
      environment:
         - discovery.type=single-node
         - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
         - MQT_VENUE=${MQT_VENUE}
         - MQT_PASS=${MQT_PASS}
      #deploy:
       #  placement:
        #       max_replicas_per_node: 1
      ports:
              - 5014:5014/udp
              - 5015:5015/udp
              - 5045:5045/udp
              - 5044:5044
      depends_on:
              - "logview-es"

 logview-kb:
      image: docker.adipsys.com:5000/logview-kb
      restart: always
      environment:
        - ELASTICSEARCH_HOSTS=http://logview-es:9200/
        - ELASTICSEARCH_USERNAME=kibana_system
        - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      #deploy:
       #  placement:
        #       max_replicas_per_node: 1
      ports:
              - ${WEB_IHM_PORT}:5601
      depends_on:
              - "logview-es"
    
 #logview-mq:
 #     image: docker.adipsys.com:5000/logview-mq
 #     restart: always
 #     environment:
 #        - MQT_VENUE=${MQT_VENUE}
 #        - MQT_PASS=${MQT_PASS}
 #     ports:
 #             - 8883:8883
 #     depends_on:
 #             - "logview-ls"
